INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   4580
        Validation size: 508
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: False

Epoch 1/5:   0%|                                                                                                                            | 0/4580 [05:42<?, ?img/s]
Traceback (most recent call last):
  File "/home/hewei/miniconda3/envs/i2dl/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hewei/miniconda3/envs/i2dl/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/hewei/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/hewei/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/hewei/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/hewei/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/hewei/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/hewei/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/hewei/TUM/Unet-pytorch/Pytorch-UNet/train.py", line 188, in <module>
    train_net(net=net,
  File "/home/hewei/TUM/Unet-pytorch/Pytorch-UNet/train.py", line 92, in train_net
    masks_pred = net(images)
  File "/home/hewei/miniconda3/envs/i2dl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hewei/TUM/Unet-pytorch/Pytorch-UNet/unet/unet_model.py", line 34, in forward
    x = self.up4(x, x1)
  File "/home/hewei/miniconda3/envs/i2dl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hewei/TUM/Unet-pytorch/Pytorch-UNet/unet/unet_parts.py", line 62, in forward
    x1 = F.pad(x1, [diffX // 2, diffX - diffX // 2,
  File "/home/hewei/miniconda3/envs/i2dl/lib/python3.10/site-packages/torch/nn/functional.py", line 4364, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 150.00 MiB (GPU 0; 3.95 GiB total capacity; 2.39 GiB already allocated; 120.69 MiB free; 2.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF